apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emberlog-api
  namespace: emberlog
spec:
  ingressClassName: traefik
  rules:
    - host: emberlog-api.pi-rack.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emberlog-api
                port:
                  number: 80
