apiVersion: v1
kind: Service
metadata:
  name: emberlog-api
  namespace: emberlog
spec:
  type: ClusterIP
  selector:
    app: emberlog-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
